name: ExplosionBattles-SNAPSHOT

author: astetyn

main: main.Main

commands:
     
    explosionbattles: 
      permission: explosionbattles.base
      description: Zakladny cmd na hracske veci
      usage: /ebd <join;leave>
      aliases: ebd
      
    explosionbattlessetup: 
       permission: explosionbattles.setup
       description: Zakladny prikaz na spravovanie minihry
       usage: /ebdsetup <option> [map]
       aliases: ebdsetup
      
permissions:
   explosionbattles.*:
     children:
        explosionbattles.base: true
        explosionbattles.setup: true
        explosionbattles.vip: true
     
   explosionbattles.vip:
     default: op
   explosionbattles.base:
     default: true
   explosionbattles.setup:
     default: op
        
version: 0.0.2 Alpha