name: ExplosionBattles

author: astetyne

main: main.Main

api-version: 1.13

commands:
     
    explosionbattles: 
      permission: explosionbattles.base
      description: Zakladny cmd na hracske veci
      usage: /eb <join ; leave ; top>
      aliases: eb
      
    explosionbattlessetup: 
       permission: explosionbattles.setup
       description: Zakladny prikaz na spravovanie minihry
       usage: /ebsetup <option> [map]
       aliases: [ebsetup, ebs]
      
permissions:
   explosionbattles.*:
     children:
        explosionbattles.base: true
        explosionbattles.setup: true
        explosionbattles.vip: true
     
   explosionbattles.vip:
     default: op
   explosionbattles.base:
     default: true
   explosionbattles.setup:
     default: op
        
version: 0.4.5 SNAPSHOT